### ISSUE TITLE
Cannot use MySQL database

### ISSUE THREAD

**Issue by democracycraft** [funkemunky/AntiVPN#3]
Consistently hitting with this error when I enable it

[23:33:30 WARN]: Exception in thread "pool-95-thread-3" java.lang.NullPointerException: Cannot invoke "com.mysql.cj.result.Row.wasNull()" because "this.thisRow" is null
[23:33:30 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.wasNull(ResultSetImpl.java:2540)
[23:33:30 WARN]:        at dev.brighten.antivpn.database.sql.MySqlVPN.getStoredResponse(MySqlVPN.java:53)
[23:33:30 WARN]:        at dev.brighten.antivpn.api.VPNExecutor.lambda$null$0(VPNExecutor.java:39)
[23:33:30 WARN]:        at java.base/java.util.HashMap.compute(HashMap.java:1320)
[23:33:30 WARN]:        at dev.brighten.antivpn.api.VPNExecutor.lambda$checkIp$1(VPNExecutor.java:37)
[23:33:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[23:33:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[23:33:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by democracycraft** [comment]
In addition to this

```[23:48:41 WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.```

**Comment by democracycraft** [comment]
Solved, superb support on Discord.
