### ISSUE TITLE
"org.bukkit.entity.Player.getAddress()" is null

### ISSUE THREAD

**Issue by WobbyChip** [funkemunky/AntiVPN#39]
[05:20:10 INFO]: UUID of player Bunger is 95608b22-7d7f-3267-b844-24cdd996c5ee
[05:20:10 INFO]: Disconnecting com.mojang.authlib.GameProfile@b65f03d[id=95608b22-7d7f-3267-b844-24cdd996c5ee,name=Bunger,properties={textures=[com.mojang.authlib.properties.Property@202388e0]},legacy=false] (/147.28.173.143:53934): You are banned from this server. Reason: The Ban Hammer has spoken!
[05:20:10 INFO]: com.mojang.authlib.GameProfile@b65f03d[id=95608b22-7d7f-3267-b844-24cdd996c5ee,name=Bunger,properties={textures=[com.mojang.authlib.properties.Property@202388e0]},legacy=false] (/147.28.173.143:53934) lost connection: You are banned from this server. Reason: The Ban Hammer has spoken!
[05:20:10 WARN]: [KauriVPN] Task #857000 for KauriVPN v1.9.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "org.bukkit.entity.Player.getAddress()" is null
	at dev.brighten.antivpn.bukkit.BukkitListener$2.run(BukkitListener.java:121) ~[KauriVPN-1.9.1.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-19]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:20:20 INFO]: Server is now paused. (Worlds saved)
[18:01:02 INFO]: Server is now resumed.
[18:01:03 INFO]: UUID of player Bunger is 95608b22-7d7f-3267-b844-24cdd996c5ee
[18:01:03 INFO]: Disconnecting com.mojang.authlib.GameProfile@5af125ba[id=95608b22-7d7f-3267-b844-24cdd996c5ee,name=Bunger,properties={textures=[com.mojang.authlib.properties.Property@6594b8c3]},legacy=false] (/147.28.173.143:46786): You are banned from this server. Reason: The Ban Hammer has spoken!
[18:01:03 WARN]: [KauriVPN] Task #967558 for KauriVPN v1.9.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "org.bukkit.entity.Player.getAddress()" is null
	at dev.brighten.antivpn.bukkit.BukkitListener$2.run(BukkitListener.java:121) ~[KauriVPN-1.9.1.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-19]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-19]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-19]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:01:03 INFO]: com.mojang.authlib.GameProfile@5af125ba[id=95608b22-7d7f-3267-b844-24cdd996c5ee,name=Bunger,properties={textures=[com.mojang.authlib.properties.Property@6594b8c3]},legacy=false] (/147.28.173.143:46786) lost connection: You are banned from this server. Reason: The Ban Hammer has spoken!

**Comment by WobbyChip** [comment]
Idk, try-catching this, so that console is not spammed would be great.

**Comment by Strahilchu** [comment]
[18:38:51 WARN]: [KauriVPN] Task #30528 for KauriVPN v1.9.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because the return value of "org.bukkit.entity.Player.getAddress()" is null
        at dev.brighten.antivpn.bukkit.BukkitListener$2.run(BukkitListener.java:121) ~[KauriVPN-1.9.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2076]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2076]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1495) ~[purpur-1.20.2.jar:git-Purpur-2076]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.20.2.jar:git-Purpur-2076]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[purpur-1.20.2.jar:git-Purpur-2076]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[purpur-1.20.2.jar:git-Purpur-2076]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[purpur-1.20.2.jar:git-Purpur-2076]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by Strahilchu** [comment]
Seems to happen when a banned player tries to join

**Comment by Strahilchu** [comment]
Can someone compile with this patch so I can use it on my Minecraft server

**Comment by WobbyChip** [comment]
> Can someone compile with this patch so I can use it on my Minecraft server

[KauriVPN-1.9.2.zip](https://github.com/funkemunky/AntiVPN/files/13321702/KauriVPN-1.9.2.zip)
