### ISSUE TITLE
Config won't generate on Velocity Proxy, error in console.

### ISSUE THREAD

**Issue by Strahilchu** [funkemunky/AntiVPN#6]
KauriVPN 1.5.1
I had manually put the config in but I got a Mysql error after updating, so I deleted the config folder and restarted the server and I'm back to this issue. Reporting since it happened in the last version as well and I think something needs fixing.

Running the plugin only on my Proxy server (Velocity 3.0.1)

[15:49:40 INFO] [dev.brighten.antivpn.velocity.VelocityPlugin]: Loading config...
[15:49:40 ERROR]: Couldn't pass ProxyInitializeEvent to kaurivpn
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878) ~[velocity.jar:3.0.1]
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:104) ~[velocity.jar:3.0.1]
        at dev.brighten.antivpn.velocity.util.Config.<init>(Config.java:34) ~[?:?]
        at dev.brighten.antivpn.velocity.VelocityPlugin.onInit(VelocityPlugin.java:53) ~[?:?]
        at dev.brighten.antivpn.velocity.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity.jar:3.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by funkemunky** [comment]
This has been resolved in an update. Sorry for not updating this issue.
