### ISSUE TITLE
MySQL Error (Plugin works fine though

### ISSUE THREAD

**Issue by Strahilchu** [funkemunky/AntiVPN#7]
[13:18:13 INFO]: [KauriVPN] Enabling KauriVPN v1.5.1
[13:18:13 INFO]: Loading config...
[13:18:13 INFO]: Starting AntiVPN services...
[13:18:13 INFO]: Using databaseType MySQL...
[13:18:13 INFO]: Initializing MySQL...
[13:18:13 WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @69f1dbef
[13:18:13 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
[13:18:13 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[13:18:13 WARN]:        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[13:18:13 WARN]:        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[13:18:13 WARN]:        at KauriVPN-1.5.1.jar//dev.brighten.antivpn.utils.MiscUtils.injectURL(MiscUtils.java:65)
[13:18:13 WARN]:        at KauriVPN-1.5.1.jar//dev.brighten.antivpn.database.sql.utils.MySQL.init(MySQL.java:24)
[13:18:13 WARN]:        at KauriVPN-1.5.1.jar//dev.brighten.antivpn.database.sql.MySqlVPN.init(MySqlVPN.java:233)
[13:18:13 WARN]:        at KauriVPN-1.5.1.jar//dev.brighten.antivpn.AntiVPN.start(AntiVPN.java:58)
[13:18:13 WARN]:        at KauriVPN-1.5.1.jar//dev.brighten.antivpn.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:41)
[13:18:13 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:18:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:18:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:18:13 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[13:18:13 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[13:18:13 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:730)
[13:18:13 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[13:18:13 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1217)
[13:18:13 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:18:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:18:13 ERROR]: [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[13:18:17 INFO]: Connection to MySQL has been established.
[13:18:17 INFO]: Creating tables...
[13:18:17 INFO]: Creating indexes...
[13:18:17 INFO]: Setting up and registering commands...

**Comment by untuned** [comment]
I get the same error. Does this have anything to do with the `--illegal-access=permit` that should be added?

```
13.11 23:15:04 [Server] INFO [KauriVPN] Enabling KauriVPN v1.5.1
13.11 23:15:04 [Server] INFO Loading config...
13.11 23:15:04 [Server] INFO Starting AntiVPN services...
13.11 23:15:04 [Server] INFO Using databaseType MySQL...
13.11 23:15:04 [Server] INFO Initializing MySQL...
13.11 23:15:04 [Server] WARN java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7a06771a
13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.utils.MiscUtils.injectURL(MiscUtils.java:65)
13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.database.sql.utils.MySQL.init(MySQL.java:24)
13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.database.sql.MySqlVPN.init(MySqlVPN.java:233)
13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.AntiVPN.start(AntiVPN.java:58)
13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:41)
13.11 23:15:04 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
13.11 23:15:04 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
13.11 23:15:04 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
13.11 23:15:04 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
13.11 23:15:04 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
13.11 23:15:04 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
13.11 23:15:04 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
13.11 23:15:04 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
13.11 23:15:04 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
13.11 23:15:04 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
13.11 23:15:04 [Server] ERROR [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
13.11 23:15:04 [Server] INFO Connection to MySQL has been established.
```

**Comment by Strahilchu** [comment]
> I get the same error. Does this have anything to do with the `--illegal-access=permit` that should be added?
> 
> ```
> 13.11 23:15:04 [Server] INFO [KauriVPN] Enabling KauriVPN v1.5.1
> 13.11 23:15:04 [Server] INFO Loading config...
> 13.11 23:15:04 [Server] INFO Starting AntiVPN services...
> 13.11 23:15:04 [Server] INFO Using databaseType MySQL...
> 13.11 23:15:04 [Server] INFO Initializing MySQL...
> 13.11 23:15:04 [Server] WARN java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @7a06771a
> 13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
> 13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
> 13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
> 13.11 23:15:04 [Server] WARN at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
> 13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.utils.MiscUtils.injectURL(MiscUtils.java:65)
> 13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.database.sql.utils.MySQL.init(MySQL.java:24)
> 13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.database.sql.MySqlVPN.init(MySqlVPN.java:233)
> 13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.AntiVPN.start(AntiVPN.java:58)
> 13.11 23:15:04 [Server] WARN at KauriVPN-1.5.1.jar//dev.brighten.antivpn.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:41)
> 13.11 23:15:04 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> 13.11 23:15:04 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
> 13.11 23:15:04 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
> 13.11 23:15:04 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
> 13.11 23:15:04 [Server] WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
> 13.11 23:15:04 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
> 13.11 23:15:04 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
> 13.11 23:15:04 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
> 13.11 23:15:04 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> 13.11 23:15:04 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:831)
> 13.11 23:15:04 [Server] ERROR [STDERR] [com.mysql.jdbc.Driver] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
> 13.11 23:15:04 [Server] INFO Connection to MySQL has been established.
> ```

I don't think so but, I am using Java 17 and that flag was removed so it's not an option for me.
It shouldn't need this flag to work afaik.
I hope dev gets a fix pushed

**Comment by MennoGamed** [comment]
Can confirm on Velocity, Java 11.

**Comment by SrBedrock** [comment]
same here, java 16
```log
[12:45:36 INFO]: Starting AntiVPN services...
[12:45:36 INFO]: Using databaseType MySQL...
[12:45:36 INFO]: Initializing MySQL...
[12:45:36 ERROR]: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @1d444652
[12:45:36 ERROR]:       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[12:45:36 ERROR]:       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[12:45:36 ERROR]:       at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[12:45:36 ERROR]:       at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[12:45:36 ERROR]:       at dev.brighten.antivpn.utils.MiscUtils.injectURL(MiscUtils.java:65)
[12:45:36 ERROR]:       at dev.brighten.antivpn.database.sql.utils.MySQL.init(MySQL.java:24)
[12:45:36 ERROR]:       at dev.brighten.antivpn.database.sql.MySqlVPN.init(MySqlVPN.java:233)
[12:45:36 ERROR]:       at dev.brighten.antivpn.AntiVPN.start(AntiVPN.java:58)
[12:45:36 ERROR]:       at dev.brighten.antivpn.bungee.BungeePlugin.onEnable(BungeePlugin.java:45)
[12:45:36 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[12:45:36 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[12:45:36 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[12:45:36 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[12:45:36 INFO]: Connection to MySQL has been established.
[12:45:36 INFO]: Creating tables...
[12:45:36 INFO]: Creating indexes...
[12:45:36 INFO]: Starting bStats metrics...
[12:45:36 INFO]: Getting strings...
[12:45:36 INFO]: Enabled plugin KauriVPN version 1.5.1 by funkemunky
```

**Comment by funkemunky** [comment]
This has been corrected in an update. Sorry for not updating the issue.
