### ISSUE TITLE
error on first start

### ISSUE THREAD

**Issue by TizoCraft** [funkemunky/AntiVPN#9]
[02:03:35 INFO]: Booting up Velocity 3.0.1...
[02:03:35 INFO]: Loading localizations...
[02:03:35 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[02:03:35 INFO]: Loading plugins...
[02:03:36 INFO]: Loaded plugin kaurivpn 1.5.0 by funkemunky
[02:03:36 INFO]: Loaded plugin spark 1.6.2 by Luck
[02:03:36 INFO]: Loaded 2 plugins
[02:03:36 INFO] [dev.brighten.antivpn.velocity.VelocityPlugin]: Loading config...
[02:03:36 ERROR]: Couldn't pass ProxyInitializeEvent to kaurivpn
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878) ~[velocity-3.0.1.jar:3.0.1]
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:104) ~[velocity-3.0.1.jar:3.0.1]
        at dev.brighten.antivpn.velocity.util.Config.<init>(Config.java:34) ~[?:?]
        at dev.brighten.antivpn.velocity.VelocityPlugin.onInit(VelocityPlugin.java:53) ~[?:?]
        at dev.brighten.antivpn.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:585) ~[velocity-3.0.1.jar:3.0.1]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:466) ~[velocity-3.0.1.jar:3.0.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[02:03:36 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:23596
[02:03:36 INFO]: Done (2.82s)!

**Comment by TizoCraft** [comment]
but after i restart again it works. just curious if this error is fatal

**Comment by funkemunky** [comment]
Yeah this has been fixed in later versions
